/**
 * End-to-end check of the render half of the pipeline: cut -> reframe ->
 * burn subtitles -> thumbnail -> upload.
 *
 * Opt-in, because it needs Postgres, MinIO and ffmpeg running:
 *
 *   RUN_MEDIA_TESTS=1 bun --env-file=../.env test render.integration
 *
 * The source is a 12-second clip generated by ffmpeg, so this downloads
 * nothing and runs no model -- it finishes in well under a minute and stays
 * inside a few hundred MB.
 */
import { test, expect, beforeAll, afterAll } from 'bun:test'
import { join } from 'node:path'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { eq } from 'drizzle-orm'

const ENABLED = process.env.RUN_MEDIA_TESTS === '1'
const maybe = ENABLED ? test : test.skip

let workDir = ''
let userId = ''
let videoId = ''
let jobId = ''
let clipId = ''

// Imported lazily: these modules validate env at import time, which would
// abort the whole test file when the suite runs without a configured .env.
let db: typeof import('./db.ts')['db']
let schema: typeof import('./db.ts')
let renderClip: typeof import('./stages/render.ts')['renderClip']
let run: typeof import('../../shared/proc.ts')['run']

beforeAll(async () => {
  if (!ENABLED) return

  const dbMod = await import('./db.ts')
  db = dbMod.db
  schema = dbMod
  renderClip = (await import('./stages/render.ts')).renderClip
  run = (await import('../../shared/proc.ts')).run

  workDir = await mkdtemp(join(tmpdir(), 'clip-test-'))

  // A 12s 640x360 source: colour bars with a tone, so there is a real video
  // and audio stream to cut, scale and map.
  const source = join(workDir, 'source.mp4')
  await run([
    'ffmpeg', '-nostdin', '-y', '-v', 'error',
    '-f', 'lavfi', '-i', 'testsrc=size=640x360:rate=25:duration=12',
    '-f', 'lavfi', '-i', 'sine=frequency=440:duration=12',
    '-c:v', 'libx264', '-preset', 'ultrafast', '-pix_fmt', 'yuv420p',
    '-c:a', 'aac', '-shortest', source,
  ])

  // Jobs have an owner since Tier C, so the fixture needs a user to hang off.
  const [user] = await db
    .insert(schema.users)
    .values({ googleSub: `test-render-${Date.now()}`, email: 'render@test.invalid' })
    .returning()
  userId = user.id

  const [video] = await db
    .insert(schema.videos)
    .values({
      url: 'test://fixture',
      platform: 'Test',
      title: 'render integration fixture',
      durationSeconds: 12,
      scratchPath: source,
    })
    .returning()
  videoId = video.id

  const [job] = await db
    .insert(schema.jobs)
    .values({
      userId,
      videoId,
      clipCount: 1,
      lengthPreset: 0,
      formats: { '9:16': true },
      burnSubtitles: true,
      status: 'rendering',
    })
    .returning()
  jobId = job.id

  const [clip] = await db
    .insert(schema.clips)
    .values({
      jobId,
      idx: 0,
      title: 'fixture clip',
      startSeconds: 1,
      endSeconds: 9,
      score: 90,
      snippet: 'hello there',
      caption: 'a caption',
      subtitleLine: 'hello\nthere',
    })
    .returning()
  clipId = clip.id
}, 120_000)

afterAll(async () => {
  if (!ENABLED) return
  await db.delete(schema.videos).where(eq(schema.videos.id, videoId)).catch(() => {})
  // Deleting the user cascades to the job and its clips.
  await db.delete(schema.users).where(eq(schema.users.id, userId)).catch(() => {})
  await rm(workDir, { recursive: true, force: true }).catch(() => {})
  await schema.pool.end().catch(() => {})
})

maybe(
  'renders a clip to 9:16 with burned subtitles and uploads it',
  async () => {
    const [clip] = await db.select().from(schema.clips).where(eq(schema.clips.id, clipId))

    await renderClip({
      jobId,
      clip,
      sourcePath: join(workDir, 'source.mp4'),
      workDir,
      ratios: ['9:16'],
      segments: [
        { start: 2, end: 5, text: 'hello there' },
        { start: 5, end: 8, text: 'this is a test' },
      ],
      burnSubtitles: true,
    })

    const [render] = await db
      .select()
      .from(schema.renders)
      .where(eq(schema.renders.clipId, clipId))

    expect(render).toBeDefined()
    expect(render.status).toBe('ready')
    expect(render.width).toBe(1080)
    expect(render.height).toBe(1920)
    expect(render.sizeBytes).toBeGreaterThan(1000)
    expect(render.s3Key).toBeTruthy()
    expect(render.thumbKey).toBeTruthy()

    // The uploads must actually be retrievable, not merely recorded.
    const body = await schema.s3.getStream(render.s3Key!)
    expect(body).toBeTruthy()

    const [after] = await db.select().from(schema.clips).where(eq(schema.clips.id, clipId))
    expect(after.status).toBe('ready')
  },
  300_000,
)
